Documentation:
  Exclude:
    - lib/lita/handlers/who_has.rb

FileName:
  Exclude:
    - lib/lita-who_has.rb

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 27

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 30
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
